// XREPORT/client/src/components/MainLayout.tsx
import { NavLink, Outlet } from 'react-router-dom';
import { BrainCircuit, FileSearch, FileStack } from 'lucide-react';
import './MainLayout.css';

const navItems = [
    { path: '/dataset', icon: FileStack, label: 'Dataset' },
    { path: '/training', icon: BrainCircuit, label: 'Training' },
    { path: '/inference', icon: FileSearch, label: 'Inference' },
];

export default function MainLayout() {
    return (
        <div className="main-layout">
            <div className="main-layout-chrome">
                <header className="app-header-bar">
                    <div className="app-header-brand">
                        <img className="app-header-logo" src="/favicon.png" alt="XREPORT logo" />
                        <div className="app-header-titles">
                            <h1 className="app-header-title">XREPORT</h1>
                            <p className="app-header-subtitle">Radiological Reports Generator</p>
                        </div>
                    </div>
                </header>

                <nav className="app-nav-bar" aria-label="Primary navigation">
                    <div className="app-nav-list">
                        {navItems.map((item) => (
                            <NavLink
                                key={item.path}
                                to={item.path}
                                className={({ isActive }) => `app-nav-button${isActive ? ' active' : ''}`}
                            >
                                <item.icon size={16} />
                                <span>{item.label}</span>
                            </NavLink>
                        ))}
                    </div>
                </nav>
            </div>

            <div className="main-layout-content">
                <Outlet />
            </div>
        </div>
    );
}

// app/client-angular/src/app/components/main-layout.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBrainCircuit, lucideFileSearch, lucideFileStack, lucideSettings } from '@ng-icons/lucide';

@Component({
  selector: 'app-main-layout',
  imports: [RouterLink, RouterLinkActive, RouterOutlet, NgIcon],
  providers: [provideIcons({ lucideBrainCircuit, lucideFileSearch, lucideFileStack, lucideSettings })],
  template: `
    <div class="main-layout">
      <div class="main-layout-chrome">
        <nav class="app-nav-bar" aria-label="Primary navigation">
          <div class="app-nav-brand">
            <img class="app-nav-logo" src="/favicon.png" alt="XREPORT logo" />
            <div class="app-nav-titles">
              <h1 class="app-nav-title">XREPORT</h1>
              <p class="app-nav-subtitle">Radiological Reports Generator</p>
            </div>
          </div>
          <div class="app-nav-list">
            <a routerLink="/inference" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" class="app-nav-button app-nav-button-primary" title="Inference" aria-label="Inference">
              <ng-icon name="lucideFileSearch" size="16" /> <span>Inference</span>
            </a>
            <span class="app-nav-separator" aria-hidden="true"></span>
            <span class="app-nav-group-label">Model development</span>
            <a routerLink="/dataset" routerLinkActive="active" class="app-nav-button" title="Dataset" aria-label="Dataset">
              <ng-icon name="lucideFileStack" size="16" /> <span>Dataset</span>
            </a>
            <a routerLink="/training" routerLinkActive="active" class="app-nav-button" title="Training" aria-label="Training">
              <ng-icon name="lucideBrainCircuit" size="16" /> <span>Training</span>
            </a>
          </div>
          <button type="button" class="app-nav-button app-nav-settings" title="Settings" aria-label="Settings" disabled>
            <ng-icon name="lucideSettings" size="16" /> <span>Settings</span>
          </button>
        </nav>
      </div>
      <div class="main-layout-content" (scroll)="onContentScroll($event)"><router-outlet /></div>
    </div>
  `,
  styleUrl: '../styles/MainLayout.css',
})
export class MainLayoutComponent {
  onContentScroll(event: Event): void {
    const element = event.target as HTMLElement;
    // The React shell resets this scroll container on route changes; route navigation starts at the top.
    if (element.scrollTop < 0) element.scrollTop = 0;
  }
}
