// XREPORT/client/src/components/CheckpointEvaluationReportModal.tsx
import { X, Calendar, ListChecks } from 'lucide-react';
import CheckpointEvaluationDashboard from './CheckpointEvaluationDashboard';
import { CheckpointEvaluationReport } from '../services/inferenceService';
import './ValidationReportModal.css';

interface CheckpointEvaluationReportModalProps {
    isOpen: boolean;
    checkpointName: string | null;
    isLoading: boolean;
    report: CheckpointEvaluationReport | null;
    error: string | null;
    progress?: number | null;
    status?: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | null;
    onClose: () => void;
}

const METRIC_LABELS: Record<string, string> = {
    evaluation_report: 'Evaluation report',
    bleu_score: 'BLEU score',
};

function formatMetricLabel(
    metric: string,
    config: { data_fraction?: number; num_samples?: number } | undefined
) {
    const label = METRIC_LABELS[metric] || metric.replace(/_/g, ' ');
    const parts: string[] = [];
    if (typeof config?.data_fraction === 'number') {
        parts.push(`${Math.round(config.data_fraction * 100)}%`);
    }
    if (typeof config?.num_samples === 'number') {
        parts.push(`${config.num_samples} samples`);
    }
    if (parts.length === 0) {
        return label;
    }
    return `${label} · ${parts.join(' · ')}`;
}

export default function CheckpointEvaluationReportModal({
    isOpen,
    checkpointName,
    isLoading,
    report,
    error,
    progress,
    status,
    onClose,
}: CheckpointEvaluationReportModalProps) {
    if (!isOpen) return null;

    const metrics = report?.metrics ?? [];
    const metricConfigs = report?.metric_configs ?? {};
    const dateLabel = report?.date ? `Generated: ${report.date}` : 'Generated: N/A';

    return (
        <div className="modal-backdrop" onClick={onClose}>
            <div className="report-modal" onClick={(e) => e.stopPropagation()}>
                <div className="report-header">
                    <div>
                        <h3>Checkpoint Evaluation Report</h3>
                        <p className="report-subtitle">
                            Checkpoint: <strong>{checkpointName || 'Unknown'}</strong>
                        </p>
                    </div>
                    <button className="report-close" onClick={onClose} aria-label="Close evaluation report">
                        <X size={18} />
                    </button>
                </div>

                <div className="report-meta">
                    <div className="report-chip">
                        <Calendar size={14} />
                        <span>{dateLabel}</span>
                    </div>
                    <div className="report-chip">
                        <ListChecks size={14} />
                        <span>{metrics.length} metrics</span>
                    </div>
                </div>

                <div className="report-metrics">
                    {(metrics.length > 0 ? metrics : ['No metrics recorded']).map(metric => (
                        <span key={metric} className="report-metric-pill">
                            {metric === 'No metrics recorded'
                                ? metric
                                : formatMetricLabel(metric, metricConfigs[metric])}
                        </span>
                    ))}
                </div>

                <div className="report-body">
                    <CheckpointEvaluationDashboard
                        isLoading={isLoading}
                        results={report?.results ?? null}
                        error={error}
                        progress={progress}
                        status={status}
                    />
                </div>
            </div>
        </div>
    );
}

// app/client/src/app/components/checkpoint-evaluation-report-modal.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBarChart2, lucideCalendar, lucideListChecks, lucideLoaderCircle, lucideX } from '@ng-icons/lucide';
import type { CheckpointEvaluationReport } from '../types/inferenceApi';
import { ModalFocusDirective } from './modal-focus.directive';

@Component({
  standalone: true,
  selector: 'app-checkpoint-evaluation-report-modal',
  imports: [CommonModule, NgIcon, ModalFocusDirective],
  providers: [provideIcons({ lucideBarChart2, lucideCalendar, lucideListChecks, lucideLoaderCircle, lucideX })],
  template: `
    @if (open) {
      <div class="modal-backdrop" role="presentation" (click)="closed.emit()"><section class="report-modal" role="dialog" aria-modal="true" aria-labelledby="checkpoint-report-title" appModalFocus (modalEscape)="closed.emit()" (click)="$event.stopPropagation()">
        <header class="report-header"><div><h3 id="checkpoint-report-title">Checkpoint Evaluation Report</h3><p class="report-subtitle">Checkpoint: <strong>{{ checkpoint || 'Unknown' }}</strong></p></div><button type="button" class="report-close" aria-label="Close evaluation report" (click)="closed.emit()"><ng-icon name="lucideX"/></button></header>
        <div class="report-meta"><span class="report-chip"><ng-icon name="lucideCalendar"/>{{ report?.date ? 'Generated: ' + report?.date : 'Generated: N/A' }}</span><span class="report-chip"><ng-icon name="lucideListChecks"/>{{ report?.metrics?.length || 0 }} metrics</span></div>
        <div class="report-metrics">@for (metric of report?.metrics || []; track metric) { <span class="report-metric-pill">{{ metricLabel(metric) }}</span> }</div>
        <div class="report-body"><div class="validation-dashboard"><div class="dashboard-header"><div class="dashboard-title"><ng-icon name="lucideBarChart2"/>Checkpoint Evaluation Results</div><span class="dashboard-status" [class.success]="hasResults()" [class.running]="loading" [class.error]="!!error">{{ statusLabel() }}</span></div>@if (loading) { <div class="loading-container"><ng-icon name="lucideLoaderCircle" class="spin"/><span class="loading-text">Running checkpoint evaluation... {{ progress ?? 0 }}%</span><div class="progress-bar"><div class="progress-fill" [style.width.%]="progress ?? 0"></div></div></div> } @else if (error) { <div class="idle-message error">{{ error }}</div> } @else if (hasResults()) { <div class="validation-content"><div class="stats-grid"><div class="stats-section"><div class="stats-section-title">Metrics</div><div class="stats-row"><span class="stat-label">Loss</span><span class="stat-value">{{ formatMetric(report?.results?.loss) }}</span></div><div class="stats-row"><span class="stat-label">Accuracy</span><span class="stat-value">{{ formatMetric(report?.results?.accuracy) }}</span></div><div class="stats-row"><span class="stat-label">BLEU Score</span><span class="stat-value">{{ formatMetric(report?.results?.bleu_score) }}</span></div></div></div></div> } @else { <div class="idle-message">Select evaluation options and run the checkpoint evaluation to see results.</div> }</div></div>
      </section></div>
    }
  `,
  styleUrls: ['../styles/ValidationReportModal.css', '../styles/ValidationDashboard.css'],
})
export class CheckpointEvaluationReportModalComponent {
  @Input() open = false;
  @Input() checkpoint: string | null = null;
  @Input() loading = false;
  @Input() error: string | null = null;
  @Input() progress: number | null = null;
  @Input() report: CheckpointEvaluationReport | null = null;
  @Output() readonly closed = new EventEmitter<void>();

  hasResults() { const results = this.report?.results; return typeof results?.loss === 'number' || typeof results?.accuracy === 'number' || typeof results?.bleu_score === 'number'; }
  formatMetric(value: number | undefined) { return typeof value === 'number' ? value.toFixed(4) : '--'; }
  statusLabel() { return this.loading ? 'Running' : this.error ? 'Error' : this.hasResults() ? 'Complete' : 'Idle'; }
  metricLabel(metric: string) {
    const labels: Record<string, string> = { evaluation_report: 'Evaluation report', bleu_score: 'BLEU score' };
    const config = this.report?.metric_configs?.[metric];
    const parts: string[] = [];
    if (typeof config?.data_fraction === 'number') parts.push(`${Math.round(config.data_fraction * 100)}%`);
    if (typeof config?.num_samples === 'number') parts.push(`${config.num_samples} samples`);
    return `${labels[metric] ?? metric.replace(/_/g, ' ')}${parts.length ? ` · ${parts.join(' · ')}` : ''}`;
  }
}
