// XREPORT/client/src/components/ValidationReportModal.tsx
import { X, Calendar, Sliders, ListChecks } from 'lucide-react';
import ValidationDashboard from './ValidationDashboard';
import { ValidationResponse } from '../services/validationService';
import './ValidationReportModal.css';

interface ValidationReportModalProps {
    isOpen: boolean;
    datasetName: string | null;
    isLoading: boolean;
    validationResult: ValidationResponse | null;
    error: string | null;
    progress?: number | null;
    status?: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | null;
    metadata?: {
        date?: string | null;
        sampleSize?: number | null;
        metrics?: string[];
    } | null;
    onClose: () => void;
}

const METRIC_LABELS: Record<string, string> = {
    pixels_distribution: 'Pixel intensity histogram',
    text_statistics: 'Text statistics',
    image_statistics: 'Image statistics',
};

function formatMetrics(metrics: string[] | undefined) {
    if (!metrics || metrics.length === 0) {
        return ['No metrics recorded'];
    }
    return metrics.map(metric => METRIC_LABELS[metric] || metric.replace(/_/g, ' '));
}

function formatSampleSize(sampleSize: number | null | undefined) {
    if (sampleSize === null || sampleSize === undefined) {
        return 'Sample size: N/A';
    }
    const pct = Math.max(0, Math.min(sampleSize, 1)) * 100;
    return `Sample size: ${pct.toFixed(0)}%`;
}

export default function ValidationReportModal({
    isOpen,
    datasetName,
    isLoading,
    validationResult,
    error,
    progress,
    status,
    metadata,
    onClose,
}: ValidationReportModalProps) {
    if (!isOpen) return null;

    const metrics = formatMetrics(metadata?.metrics);
    const sampleLabel = formatSampleSize(metadata?.sampleSize);
    const dateLabel = metadata?.date ? `Generated: ${metadata.date}` : 'Generated: N/A';

    return (
        <div className="modal-backdrop" onClick={onClose}>
            <div className="report-modal" onClick={(e) => e.stopPropagation()}>
                <div className="report-header">
                    <div>
                        <h3>Validation Report</h3>
                        <p className="report-subtitle">
                            Dataset: <strong>{datasetName || 'Unknown'}</strong>
                        </p>
                    </div>
                    <button className="report-close" onClick={onClose} aria-label="Close validation report">
                        <X size={18} />
                    </button>
                </div>

                <div className="report-meta">
                    <div className="report-chip">
                        <Calendar size={14} />
                        <span>{dateLabel}</span>
                    </div>
                    <div className="report-chip">
                        <Sliders size={14} />
                        <span>{sampleLabel}</span>
                    </div>
                    <div className="report-chip">
                        <ListChecks size={14} />
                        <span>{metrics.length} metrics</span>
                    </div>
                </div>

                <div className="report-metrics">
                    {metrics.map(metric => (
                        <span key={metric} className="report-metric-pill">
                            {metric}
                        </span>
                    ))}
                </div>

                <div className="report-body">
                    <ValidationDashboard
                        isLoading={isLoading}
                        validationResult={validationResult}
                        error={error}
                        progress={progress}
                        status={status}
                    />
                </div>
            </div>
        </div>
    );
}

// app/client/src/app/components/validation-report-modal.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideBarChart2, lucideCalendar, lucideFileText, lucideImage, lucideListChecks, lucideLoaderCircle, lucideSliders, lucideX } from '@ng-icons/lucide';
import type { ValidationResponse } from '../types/validationApi';
import { ModalFocusDirective } from './modal-focus.directive';

type ReportStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | null | undefined;

@Component({
  standalone: true,
  selector: 'app-validation-report-modal',
  imports: [CommonModule, NgIcon, ModalFocusDirective],
  providers: [provideIcons({ lucideBarChart2, lucideCalendar, lucideFileText, lucideImage, lucideListChecks, lucideLoaderCircle, lucideSliders, lucideX })],
  template: `
    @if (open) {
      <div class="modal-backdrop" role="presentation" (click)="closed.emit()">
        <section class="report-modal" role="dialog" aria-modal="true" aria-labelledby="validation-report-title" appModalFocus (modalEscape)="closed.emit()" (click)="$event.stopPropagation()">
          <header class="report-header"><div><h3 id="validation-report-title">Validation Report</h3><p class="report-subtitle">Dataset: <strong>{{ datasetName || 'Unknown' }}</strong></p></div><button type="button" class="report-close" aria-label="Close validation report" (click)="closed.emit()"><ng-icon name="lucideX"/></button></header>
          <div class="report-meta"><span class="report-chip"><ng-icon name="lucideCalendar"/>{{ metadata?.date ? 'Generated: ' + metadata?.date : 'Generated: N/A' }}</span><span class="report-chip"><ng-icon name="lucideSliders"/>{{ sampleLabel() }}</span><span class="report-chip"><ng-icon name="lucideListChecks"/>{{ metricLabels().length }} metrics</span></div>
          <div class="report-metrics">@for (metric of metricLabels(); track metric) { <span class="report-metric-pill">{{ metric }}</span> }</div>
          <div class="report-body">
            @if (loading) { <div class="loading-container"><ng-icon name="lucideLoaderCircle" class="spin"/><span class="loading-text">{{ status === 'pending' ? 'Queued' : 'Running' }} validation... {{ progress ?? 0 }}%</span><div class="progress-track"><span [style.width.%]="progress ?? 0"></span></div></div> }
            @else if (error) { <div class="idle-message error">{{ error }}</div> }
            @else if (result; as report) {
              <p class="result-message">{{ report.message }}</p>
              <div class="stats-grid">
                @if (report.text_statistics; as text) { <div class="stats-section"><div class="stats-section-title"><ng-icon name="lucideFileText"/>Text Statistics</div><div class="stats-row"><span class="stat-label">Total Reports</span><span class="stat-value highlight">{{ text.count | number }}</span></div><div class="stats-row"><span class="stat-label">Total Words</span><span class="stat-value">{{ text.total_words | number }}</span></div><div class="stats-row"><span class="stat-label">Unique Words</span><span class="stat-value">{{ text.unique_words | number }}</span></div><div class="stats-row"><span class="stat-label">Avg Words/Report</span><span class="stat-value">{{ text.avg_words_per_report | number:'1.1-1' }}</span></div></div> }
                @if (report.image_statistics; as image) { <div class="stats-section"><div class="stats-section-title"><ng-icon name="lucideImage"/>Image Statistics</div><div class="stats-row"><span class="stat-label">Total Images</span><span class="stat-value highlight">{{ image.count | number }}</span></div><div class="stats-row"><span class="stat-label">Avg Height</span><span class="stat-value">{{ image.mean_height | number:'1.0-0' }} px</span></div><div class="stats-row"><span class="stat-label">Avg Width</span><span class="stat-value">{{ image.mean_width | number:'1.0-0' }} px</span></div><div class="stats-row"><span class="stat-label">Avg Pixel Value</span><span class="stat-value">{{ image.mean_pixel_value | number:'1.2-2' }}</span></div></div> }
              </div>
              @if (report.pixel_distribution; as pixels) { <div class="chart-section"><div class="chart-title"><ng-icon name="lucideBarChart2"/>Pixel Intensity Distribution</div><div class="histogram" role="img" aria-label="Pixel intensity distribution">@for (bar of histogram(pixels.counts); track $index) { <span class="histogram-bar" [style.height.%]="bar" [attr.title]="($index * 4) + ' intensity'"></span> }</div><div class="chart-axis"><span>0</span><span>64</span><span>128</span><span>192</span><span>255</span></div></div> }
            } @else { <div class="idle-message">No validation report is available yet.</div> }
          </div>
        </section>
      </div>
    }
  `,
  styleUrls: ['../styles/ValidationReportModal.css', '../styles/ValidationDashboard.css'],
})
export class ValidationReportModalComponent {
  @Input() open = false;
  @Input() datasetName: string | null = null;
  @Input() loading = false;
  @Input() result: ValidationResponse | null = null;
  @Input() error: string | null = null;
  @Input() progress: number | null = null;
  @Input() status: ReportStatus = null;
  @Input() metadata: { date?: string | null; sampleSize?: number | null; metrics?: string[] } | null = null;
  @Output() readonly closed = new EventEmitter<void>();
  private readonly labels: Record<string, string> = { pixels_distribution: 'Pixel intensity histogram', text_statistics: 'Text statistics', image_statistics: 'Image statistics' };
  metricLabels() { return (this.metadata?.metrics ?? []).length ? (this.metadata?.metrics ?? []).map((metric) => this.labels[metric] ?? metric.replace(/_/g, ' ')) : ['No metrics recorded']; }
  sampleLabel() { return this.metadata?.sampleSize == null ? 'Sample size: N/A' : `Sample size: ${Math.max(0, Math.min(this.metadata.sampleSize, 1)) * 100}%`; }
  histogram(counts: number[]) { const bins: number[] = []; for (let index = 0; index < Math.min(256, counts.length); index += 4) bins.push(counts.slice(index, index + 4).reduce((sum, value) => sum + value, 0)); const max = Math.max(...bins, 1); return bins.map((value) => Math.max(2, value / max * 100)); }
}
