// app/client/src/app/components/new-training-wizard.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output, signal } from '@angular/core';
import { FormGroup, ReactiveFormsModule } from '@angular/forms';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideActivity, lucideChevronLeft, lucideChevronRight, lucideCpu, lucideInfo, lucideMonitor, lucidePlay, lucideSettings, lucideX } from '@ng-icons/lucide';
import { ModalFocusDirective } from './modal-focus.directive';

@Component({
  standalone: true,
  selector: 'app-new-training-wizard',
  imports: [CommonModule, ReactiveFormsModule, NgIcon, ModalFocusDirective],
  providers: [provideIcons({ lucideActivity, lucideChevronLeft, lucideChevronRight, lucideCpu, lucideInfo, lucideMonitor, lucidePlay, lucideSettings, lucideX })],
  styleUrl: '../styles/TrainingPage.css',
  template: `
    @if (open) {
      <div class="training-modal-backdrop" role="presentation">
        <section class="modal training-wizard-modal" role="dialog" aria-modal="true" aria-labelledby="new-training-title" appModalFocus (modalEscape)="closed.emit()">
          <div class="modal-header"><h2 id="new-training-title">New Training Wizard</h2><button type="button" class="btn-icon-small" aria-label="Close" (click)="closed.emit()"><ng-icon name="lucideX"/></button></div>
          <p>Dataset: <strong>{{ datasetLabel || 'No dataset selected' }}</strong></p>
          <nav class="training-wizard-steps" aria-label="Training configuration steps">
            @for (step of steps; track step; let index = $index) {
              <button type="button" class="training-wizard-step" [class.active]="currentStep() === index" [attr.aria-current]="currentStep() === index ? 'step' : null" (click)="goToStep(index)"><span>{{ index + 1 }}</span>{{ step }}</button>
            }
          </nav>
          <div class="training-wizard-body" [formGroup]="form">
            @if (currentStep() === 0) {
              <div class="wizard-page"><div class="wizard-section-title"><ng-icon name="lucideCpu"/><span>Model Architecture</span></div><div class="wizard-2col-panel">
                <div class="wizard-col"><label class="form-group"><span class="form-label">Encoders</span><input class="form-input" type="number" min="1" formControlName="numEncoders"/></label><label class="form-group"><span class="form-label">Decoders</span><input class="form-input" type="number" min="1" formControlName="numDecoders"/></label><label class="form-group"><span class="form-label">Embedding dimensions</span><input class="form-input" type="number" min="1" step="8" formControlName="embeddingDims"/></label><label class="form-group"><span class="form-label">Attention heads</span><input class="form-input" type="number" min="1" formControlName="attnHeads"/></label></div>
                <div class="wizard-col"><label class="form-group"><span class="form-label">Temperature</span><input class="form-input" type="number" min="0" step="0.05" formControlName="trainTemp"/></label><label class="checkbox-label"><input type="checkbox" formControlName="freezeImgEncoder"/> Freeze image encoder</label></div>
              </div></div>
            }
            @if (currentStep() === 1) {
              <div class="wizard-page"><div class="wizard-section-title"><ng-icon name="lucideSettings"/><span>Dataset Configuration</span></div><div class="wizard-2col-panel">
                <div class="wizard-col"><label class="checkbox-label"><input type="checkbox" formControlName="useImgAugment"/> Enable image augmentation</label></div>
                <div class="wizard-col"><label class="checkbox-label"><input type="checkbox" formControlName="shuffleWithBuffer"/> Shuffle with buffer</label><label class="form-group"><span class="form-label">Shuffle buffer size</span><input class="form-input" type="number" min="1" formControlName="shuffleBufferSize" [disabled]="!form.get('shuffleWithBuffer')?.value"/></label></div>
              </div></div>
            }
            @if (currentStep() === 2) {
              <div class="wizard-page"><div class="wizard-section-title"><ng-icon name="lucideActivity"/><span>Training Parameters</span></div><div class="wizard-2col-panel">
                <div class="wizard-col"><label class="form-group"><span class="form-label">Epochs</span><input class="form-input" type="number" min="1" formControlName="epochs"/></label><label class="form-group"><span class="form-label">Batch size</span><input class="form-input" type="number" min="1" formControlName="batchSize"/></label><label class="checkbox-label"><input type="checkbox" formControlName="saveCheckpoints"/> Save checkpoints</label></div>
                <div class="wizard-col"><label class="checkbox-label"><input type="checkbox" formControlName="useScheduler"/> Use learning-rate scheduler</label><label class="form-group"><span class="form-label">Target learning rate</span><input class="form-input" type="number" min="0" step="0.0001" formControlName="targetLR" [disabled]="!form.get('useScheduler')?.value"/></label><label class="form-group"><span class="form-label">Warmup steps</span><input class="form-input" type="number" min="0" formControlName="warmupSteps" [disabled]="!form.get('useScheduler')?.value"/></label></div>
              </div></div>
            }
            @if (currentStep() === 3) {
              <div class="wizard-page"><div class="wizard-section-title"><ng-icon name="lucideMonitor"/><span>Device Configuration</span></div><div class="wizard-2col-panel">
                <div class="wizard-col"><label class="checkbox-label"><input type="checkbox" formControlName="useGpu"/> Enable GPU</label><label class="form-group"><span class="form-label">GPU device</span><select class="form-select" formControlName="gpuId" [disabled]="!form.get('useGpu')?.value"><option [ngValue]="0">0</option><option [ngValue]="1">1</option><option [ngValue]="2">2</option><option [ngValue]="3">3</option></select></label><label class="checkbox-label"><input type="checkbox" formControlName="pinMemory"/> Pin memory</label><label class="checkbox-label"><input type="checkbox" formControlName="useMixedPrecision"/> Mixed precision</label><label class="checkbox-label"><input type="checkbox" formControlName="realTimePlot"/> Plot training metrics</label></div>
                <div class="wizard-col"><label class="form-group"><span class="form-label">Dataloader workers</span><input class="form-input" type="number" min="0" formControlName="dataloaderWorkers"/></label><label class="form-group"><span class="form-label">Prefetch factor</span><input class="form-input" type="number" min="1" formControlName="prefetchFactor" [disabled]="!form.get('dataloaderWorkers')?.value"/></label><label class="checkbox-label"><input type="checkbox" formControlName="persistentWorkers" [disabled]="!form.get('dataloaderWorkers')?.value"/> Persistent workers</label><label class="checkbox-label"><input type="checkbox" formControlName="jitCompile"/> Enable torch compile</label><label class="form-group"><span class="form-label">Compile backend</span><select class="form-select" formControlName="jitBackend" [disabled]="!form.get('jitCompile')?.value"><option value="inductor">inductor</option><option value="eager">eager</option><option value="aot_eager">aot_eager</option><option value="nvprims_nvfuser">nvprims_nvfuser</option></select></label></div>
              </div></div>
            }
            @if (currentStep() === 4) {
              <div class="wizard-page"><div class="wizard-section-title"><ng-icon name="lucideInfo"/><span>Training Summary</span></div><div class="wizard-summary-content"><div class="wizard-summary"><div class="summary-section"><h5>Model</h5><div class="summary-item"><span>Encoders</span><span>{{ form.get('numEncoders')?.value }}</span></div><div class="summary-item"><span>Decoders</span><span>{{ form.get('numDecoders')?.value }}</span></div><div class="summary-item"><span>Embedding</span><span>{{ form.get('embeddingDims')?.value }}</span></div><div class="summary-item"><span>Heads</span><span>{{ form.get('attnHeads')?.value }}</span></div></div><div class="summary-section"><h5>Training</h5><div class="summary-item"><span>Epochs</span><span>{{ form.get('epochs')?.value }}</span></div><div class="summary-item"><span>Batch size</span><span>{{ form.get('batchSize')?.value }}</span></div><div class="summary-item"><span>Scheduler</span><span>{{ form.get('useScheduler')?.value ? 'Yes' : 'No' }}</span></div><div class="summary-item"><span>Checkpoints</span><span>{{ form.get('saveCheckpoints')?.value ? 'Yes' : 'No' }}</span></div></div><div class="summary-section"><h5>Runtime</h5><div class="summary-item"><span>Device</span><span>{{ form.get('useGpu')?.value ? 'GPU ' + form.get('gpuId')?.value : 'CPU' }}</span></div><div class="summary-item"><span>Workers</span><span>{{ form.get('dataloaderWorkers')?.value }}</span></div><div class="summary-item"><span>Mixed precision</span><span>{{ form.get('useMixedPrecision')?.value ? 'Yes' : 'No' }}</span></div><div class="summary-item"><span>Torch compile</span><span>{{ form.get('jitCompile')?.value ? form.get('jitBackend')?.value : 'No' }}</span></div></div></div></div></div>
            }
          </div>
          @if (error) { <div class="upload-status error">{{ error }}</div> }
          <div class="modal-footer training-wizard-actions"><button type="button" class="btn btn-secondary" (click)="closed.emit()">Cancel</button>@if (currentStep() > 0) { <button type="button" class="btn btn-secondary" (click)="previousStep()"><ng-icon name="lucideChevronLeft"/>Back</button> }@if (currentStep() < steps.length - 1) { <button type="button" class="btn btn-primary" (click)="nextStep()">Next<ng-icon name="lucideChevronRight"/></button> }@else { <button type="button" class="btn btn-primary" (click)="submitted.emit()" [disabled]="isLoading || form.invalid"><ng-icon [name]="isLoading ? 'lucideActivity' : 'lucidePlay'"/>{{ isLoading ? 'Starting…' : 'Start training' }}</button> }</div>
        </section>
      </div>
    }
  `,
})
export class NewTrainingWizardComponent {
  private openState = false;
  @Input()
  get open() { return this.openState; }
  set open(value: boolean) { if (value && !this.openState) this.currentStep.set(0); this.openState = value; }
  @Input() datasetLabel = '';
  @Input() form!: FormGroup;
  @Input() isLoading = false;
  @Input() error: string | null = null;
  @Output() readonly closed = new EventEmitter<void>();
  @Output() readonly submitted = new EventEmitter<void>();
  readonly steps = ['Model', 'Dataset', 'Training', 'Device', 'Summary'];
  readonly currentStep = signal(0);
  nextStep() { this.currentStep.update((step) => Math.min(step + 1, this.steps.length - 1)); }
  previousStep() { this.currentStep.update((step) => Math.max(step - 1, 0)); }
  goToStep(step: number) { this.currentStep.set(Math.max(0, Math.min(step, this.steps.length - 1))); }
}

// XREPORT/client/src/components/NewTrainingWizard.tsx
import { useState, useEffect } from 'react';
import {
    Activity,
    ChevronLeft,
    ChevronRight,
    Cpu,
    Info,
    Monitor,
    Play,
    Settings,
    X,
} from 'lucide-react';
import { TrainingConfig } from '../types';
import WizardSteps from './WizardSteps';
import FormCheckbox from './shared/FormCheckbox';
import '../pages/TrainingPage.css';

interface NewTrainingWizardProps {
    isOpen: boolean;
    config: TrainingConfig;
    onConfigChange: (key: keyof TrainingConfig, value: TrainingConfig[keyof TrainingConfig]) => void;
    onClose: () => void;
    onConfirm: (checkpointName: string) => void;
    isLoading: boolean;
    selectedDatasetLabel: string;
    error: string | null;
}

export default function NewTrainingWizard({
    isOpen,
    config,
    onConfigChange,
    onClose,
    onConfirm,
    isLoading,
    selectedDatasetLabel,
    error,
}: NewTrainingWizardProps) {
    const steps = ['Model', 'Dataset', 'Training', 'Device', 'Summary'];
    const jitBackendOptions = ['inductor', 'eager', 'aot_eager', 'nvprims_nvfuser'];
    const [currentPage, setCurrentPage] = useState(0);
    const [checkpointName, setCheckpointName] = useState('');

    useEffect(() => {
        if (isOpen) {
            setCurrentPage(0);
            setCheckpointName('');
        }
    }, [isOpen]);

    if (!isOpen) return null;

    const canConfirm = Boolean(selectedDatasetLabel);
    const isLastPage = currentPage === steps.length - 1;

    const handleConfirm = () => {
        let finalName = checkpointName.trim();
        if (!finalName) {
            const timestamp = new Date().toISOString().replace(/[-:.]/g, '').slice(0, 15);
            finalName = `XREPORT_e${config.numEncoders}_d${config.numDecoders}_${timestamp}`;
        }
        onConfirm(finalName);
    };

    return (
        <div className="training-modal-backdrop">
            <div className="training-wizard-modal">
                <div className="training-wizard-header">
                    <div>
                        <h3>New Training Wizard</h3>
                        <p>Dataset: <strong>{selectedDatasetLabel || 'No dataset selected'}</strong></p>
                    </div>
                    <button className="training-wizard-close" onClick={onClose} aria-label="Close wizard">
                        <X size={18} />
                    </button>
                </div>
                <WizardSteps steps={steps} current={currentPage} />

                <div className="training-wizard-body">
                    {currentPage === 0 && (
                        <div className="wizard-page">
                            <div className="wizard-section-title">
                                <Cpu size={16} />
                                <span>Model Architecture</span>
                            </div>
                            <div className="wizard-2col-panel">
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label">Encoders</label>
                                        <input
                                            type="number"
                                            className="form-input"
                                            value={config.numEncoders}
                                            onChange={(e) => onConfigChange('numEncoders', parseInt(e.target.value, 10))}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Decoders</label>
                                        <input
                                            type="number"
                                            className="form-input"
                                            value={config.numDecoders}
                                            onChange={(e) => onConfigChange('numDecoders', parseInt(e.target.value, 10))}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Embedding Dims</label>
                                        <input
                                            type="number"
                                            step="8"
                                            className="form-input"
                                            value={config.embeddingDims}
                                            onChange={(e) => onConfigChange('embeddingDims', parseInt(e.target.value, 10))}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Attention Heads</label>
                                        <input
                                            type="number"
                                            className="form-input"
                                            value={config.attnHeads}
                                            onChange={(e) => onConfigChange('attnHeads', parseInt(e.target.value, 10))}
                                        />
                                    </div>
                                </div>
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label">Temperature</label>
                                        <input
                                            type="number"
                                            step="0.05"
                                            className="form-input"
                                            value={config.trainTemp}
                                            onChange={(e) => onConfigChange('trainTemp', parseFloat(e.target.value))}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label form-label-placeholder">Encoders</label>
                                        <FormCheckbox
                                            checked={config.freezeImgEncoder}
                                            label="Freeze Encoder"
                                            onChange={(checked) => onConfigChange('freezeImgEncoder', checked)}
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {currentPage === 1 && (
                        <div className="wizard-page">
                            <div className="wizard-section-title">
                                <Settings size={16} />
                                <span>Dataset Configuration</span>
                            </div>
                            <div className="wizard-2col-panel">
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label">Image Augmentation</label>
                                        <FormCheckbox
                                            checked={config.useImgAugment}
                                            label="Enable Augmentation"
                                            onChange={(checked) => onConfigChange('useImgAugment', checked)}
                                        />
                                    </div>
                                </div>
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label form-label-transparent">Shuffle</label>
                                        <div className="wizard-inline-row">
                                            <FormCheckbox
                                                checked={config.shuffleWithBuffer}
                                                label="Shuffle"
                                                className="form-checkbox-no-margin"
                                                onChange={(checked) => onConfigChange('shuffleWithBuffer', checked)}
                                            />
                                            {config.shuffleWithBuffer && (
                                                <input
                                                    type="number"
                                                    step="10"
                                                    className="form-input shuffle-buffer-input"
                                                    placeholder="Buffer"
                                                    value={config.shuffleBufferSize}
                                                    onChange={(e) => onConfigChange('shuffleBufferSize', parseInt(e.target.value, 10))}
                                                />
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {currentPage === 2 && (
                        <div className="wizard-page">
                            <div className="wizard-section-title">
                                <Activity size={16} />
                                <span>Training Parameters</span>
                            </div>
                            <div className="wizard-2col-panel">
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label">Epochs</label>
                                        <input
                                            type="number"
                                            className="form-input"
                                            value={config.epochs}
                                            onChange={(e) => onConfigChange('epochs', parseInt(e.target.value, 10))}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Batch Size</label>
                                        <input
                                            type="number"
                                            className="form-input"
                                            value={config.batchSize}
                                            onChange={(e) => onConfigChange('batchSize', parseInt(e.target.value, 10))}
                                        />
                                    </div>
                                </div>
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label form-label-placeholder">Save Checkpoints</label>
                                        <FormCheckbox
                                            checked={config.saveCheckpoints}
                                            label="Save Checkpoints"
                                            onChange={(checked) => onConfigChange('saveCheckpoints', checked)}
                                        />
                                    </div>
                                </div>
                            </div>

                            <div className="wizard-separator" />

                            <div className="wizard-2col-panel">
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <FormCheckbox
                                            checked={config.useScheduler}
                                            label="Use LR Scheduler"
                                            onChange={(checked) => onConfigChange('useScheduler', checked)}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Target Learning Rate</label>
                                        <input
                                            type="number"
                                            step="0.0001"
                                            className="form-input"
                                            value={config.targetLR}
                                            onChange={(e) => onConfigChange('targetLR', parseFloat(e.target.value))}
                                            disabled={!config.useScheduler}
                                        />
                                    </div>
                                </div>
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label">Warmup Steps</label>
                                        <input
                                            type="number"
                                            className="form-input"
                                            value={config.warmupSteps}
                                            onChange={(e) => onConfigChange('warmupSteps', parseInt(e.target.value, 10))}
                                            disabled={!config.useScheduler}
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {currentPage === 3 && (
                        <div className="wizard-page">
                            <div className="wizard-section-title">
                                <Monitor size={16} />
                                <span>Device Configuration</span>
                            </div>
                            <div className="wizard-2col-panel">
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <label className="form-label">Dataloader Workers</label>
                                        <input
                                            type="number"
                                            min={0}
                                            className="form-input"
                                            value={config.dataloaderWorkers}
                                            onChange={(e) => onConfigChange('dataloaderWorkers', parseInt(e.target.value, 10))}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Prefetch Factor</label>
                                        <input
                                            type="number"
                                            min={1}
                                            className="form-input"
                                            value={config.prefetchFactor}
                                            onChange={(e) => onConfigChange('prefetchFactor', parseInt(e.target.value, 10))}
                                            disabled={config.dataloaderWorkers === 0}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <FormCheckbox
                                            checked={config.pinMemory}
                                            label="Pin Memory"
                                            onChange={(checked) => onConfigChange('pinMemory', checked)}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <FormCheckbox
                                            checked={config.persistentWorkers}
                                            label="Persistent Workers"
                                            disabled={config.dataloaderWorkers === 0}
                                            onChange={(checked) => onConfigChange('persistentWorkers', checked)}
                                        />
                                    </div>
                                </div>
                                <div className="wizard-col">
                                    <div className="form-group">
                                        <FormCheckbox
                                            checked={config.useGpu}
                                            label="Enable GPU"
                                            onChange={(checked) => onConfigChange('useGpu', checked)}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Device</label>
                                        <input
                                            type="number"
                                            min={0}
                                            className="form-input"
                                            value={config.gpuId}
                                            onChange={(e) => onConfigChange('gpuId', parseInt(e.target.value, 10))}
                                            disabled={!config.useGpu}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <FormCheckbox
                                            checked={config.jitCompile}
                                            label="Enable Torch Compile"
                                            onChange={(checked) => onConfigChange('jitCompile', checked)}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Backend</label>
                                        <select
                                            className="form-select"
                                            value={config.jitBackend}
                                            onChange={(e) => onConfigChange('jitBackend', e.target.value)}
                                            disabled={!config.jitCompile}
                                        >
                                            {jitBackendOptions.map((backend) => (
                                                <option key={backend} value={backend}>{backend}</option>
                                            ))}
                                        </select>
                                    </div>
                                    <div className="form-group">
                                        <FormCheckbox
                                            checked={config.useMixedPrecision}
                                            label="Enable Mixed Precision"
                                            onChange={(checked) => onConfigChange('useMixedPrecision', checked)}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <FormCheckbox
                                            checked={config.realTimePlot}
                                            label="Plot Training Metrics"
                                            onChange={(checked) => onConfigChange('realTimePlot', checked)}
                                        />
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}

                    {currentPage === 4 && (
                        <div className="wizard-page">
                            <div className="wizard-section-title">
                                <Info size={16} />
                                <span>Training Summary</span>
                            </div>

                            <div className="form-group checkpoint-name-group">
                                <label className="form-label">Training Checkpoint Name</label>
                                <input
                                    type="text"
                                    className="form-input highlight-input"
                                    placeholder="e.g. My_Experiment_v1 (Optional)"
                                    value={checkpointName}
                                    onChange={(e) => setCheckpointName(e.target.value)}
                                />
                                <span className="form-help">Unique name for this training run. If empty, a default name will be generated.</span>
                            </div>

                            <div className="wizard-summary-content">
                                <div className="wizard-summary">
                                    <div className="summary-section">
                                        <h5>Model</h5>
                                        <div className="summary-item"><label>Encoders:</label> <span>{config.numEncoders}</span></div>
                                        <div className="summary-item"><label>Decoders:</label> <span>{config.numDecoders}</span></div>
                                        <div className="summary-item"><label>Embedding:</label> <span>{config.embeddingDims}</span></div>
                                        <div className="summary-item"><label>Heads:</label> <span>{config.attnHeads}</span></div>
                                    </div>
                                    <div className="summary-section">
                                        <h5>Training</h5>
                                        <div className="summary-item"><label>Epochs:</label> <span>{config.epochs}</span></div>
                                        <div className="summary-item"><label>Batch Size:</label> <span>{config.batchSize}</span></div>
                                        <div className="summary-item"><label>LR Scheduler:</label> <span>{config.useScheduler ? 'Yes' : 'No'}</span></div>
                                        <div className="summary-item"><label>Target LR:</label> <span>{config.targetLR}</span></div>
                                    </div>
                                    <div className="summary-section">
                                        <h5>Options</h5>
                                        <div className="summary-item"><label>Augment:</label> <span>{config.useImgAugment ? 'Yes' : 'No'}</span></div>
                                        <div className="summary-item"><label>Shuffle:</label> <span>{config.shuffleWithBuffer ? `Yes (${config.shuffleBufferSize})` : 'No'}</span></div>
                                        <div className="summary-item"><label>Checkpoints:</label> <span>{config.saveCheckpoints ? 'Yes' : 'No'}</span></div>
                                        <div className="summary-item"><label>Freeze:</label> <span>{config.freezeImgEncoder ? 'Yes' : 'No'}</span></div>
                                        <div className="summary-item"><label>GPU:</label> <span>{config.useGpu ? `cuda:${config.gpuId}` : 'CPU'}</span></div>
                                        <div className="summary-item"><label>Workers:</label> <span>{config.dataloaderWorkers}</span></div>
                                        <div className="summary-item"><label>Prefetch:</label> <span>{config.dataloaderWorkers > 0 ? config.prefetchFactor : 'N/A'}</span></div>
                                        <div className="summary-item"><label>Pin Memory:</label> <span>{config.pinMemory ? 'Yes' : 'No'}</span></div>
                                        <div className="summary-item"><label>Persistent:</label> <span>{config.persistentWorkers ? 'Yes' : 'No'}</span></div>
                                        <div className="summary-item"><label>Mixed Precision:</label> <span>{config.useMixedPrecision ? 'Yes' : 'No'}</span></div>
                                        <div className="summary-item"><label>Torch Compile:</label> <span>{config.jitCompile ? `Yes (${config.jitBackend})` : 'No'}</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                <div className="training-wizard-footer">
                    {error && <span className="wizard-error">{error}</span>}
                    <div className="wizard-actions">
                        <button className="btn btn-secondary" onClick={onClose} disabled={isLoading}>
                            Cancel
                        </button>
                        {currentPage > 0 && (
                            <button
                                className="btn btn-secondary"
                                onClick={() => setCurrentPage((prev) => Math.max(prev - 1, 0))}
                                disabled={isLoading}
                            >
                                <ChevronLeft size={16} />
                                Back
                            </button>
                        )}
                        {!isLastPage && (
                            <button
                                className="btn btn-primary"
                                onClick={() => setCurrentPage((prev) => Math.min(prev + 1, steps.length - 1))}
                                disabled={isLoading}
                            >
                                Next
                                <ChevronRight size={16} />
                            </button>
                        )}
                        {isLastPage && (
                            <button
                                className="btn btn-primary"
                                onClick={handleConfirm}
                                disabled={!canConfirm || isLoading}
                            >
                                <Play size={16} />
                                {isLoading ? 'Starting...' : 'Start Training'}
                            </button>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
